# Step 1: Build React
FROM node:18 AS build-stage
WORKDIR /app

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/suneethabulla/bloodbanking-system.git .

WORKDIR /app/frontend

RUN npm install
RUN npm run build

# Step 2: Serve using Tomcat
FROM tomcat:9-jdk17

RUN rm -rf /usr/local/tomcat/webapps/*

# Serve frontend as ROOT
COPY --from=build-stage /app/frontend/dist /usr/local/tomcat/webapps/ROOT

EXPOSE 8080
CMD ["catalina.sh", "run"]
